prefixEmpty:
	echo "empty prefix: "
	cat this_file_not_exist
	echo "error not show"

prefixAt:
	@echo "prefix at: "
	@cat this_file_not_exist
	@echo "error not show"

prefixMinus:
	-echo "prefix minus: "
	-cat this_file_not_exist
	-@echo "this after error show"