.PHONY: test check clean build dist all

include MakefileUtils/MakeDistTools.mk
include MakefileUtils/MakeDistToolsExtraFreebsd.mk
include MakefileUtils/MakeDistToolsExtraOpenbsd.mk
include MakefileUtils/MakeDistToolsExtraNetbsd.mk

all:
	@echo "all task"